-- ARCOVA CRM — RLS legacy marker
--
-- This file is intentionally non-executable.
-- The live ARCOVA database now uses the enterprise RBAC model:
--   app_roles
--   app_permissions
--   app_role_permissions
--   private.current_role()
--   private.has_permission()
--   private.can_access_user()
--   private.can_access_lead()
--
-- Role assignment is controlled through the Admin/CEO Team Controller.
-- Data access is enforced by Supabase RLS in the live project.
--
-- Do not use this legacy snapshot for new schema changes.
-- Add future changes as a versioned Supabase migration after reviewing
-- the current live schema and advisors.
