import { useRouter } from 'next/router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../supabaseClient';
import { can, normalizeRole, PERMISSIONS } from '../../lib/permissions';

const T={page:{minHeight:'100vh',background:'#f5efe3',color:'#3f321f',padding:16,fontFamily:'Tahoma,"Segoe UI",Arial,sans-serif',direction:'rtl'},shell:{maxWidth:1240,margin:'0 auto'},card:{background:'#fffaf0',border:'1px solid #d9c5a4',borderRadius:16,padding:18,marginBottom:16,boxShadow:'0 8px 24px rgba(118,85,34,.06)'},title:{color:'#765522',margin:'0 0 12px'},muted:{color:'#806f56'},button:{border:'1px solid #b08a4a',background:'#b08a4a',color:'#fffaf0',borderRadius:10,padding:'9px 13px',fontWeight:700,cursor:'pointer'},secondary:{border:'1px solid #d9c5a4',background:'#fffaf0',color:'#765522',borderRadius:10,padding:'9px 13px',fontWeight:700,cursor:'pointer'},danger:{border:'1px solid #b65443',background:'#fff7f4',color:'#9b3e30',borderRadius:10,padding:'9px 13px',fontWeight:700,cursor:'pointer'},input:{width:'100%',minWidth:0,padding:10,border:'1px solid #d9c5a4',borderRadius:10,background:'#fffaf0',color:'#3f321f',fontFamily:'inherit',letterSpacing:'normal'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}};
const text=v=>v===null||v===undefined||v===''?'غير محدد':String(v);
const date=v=>v?new Date(v).toLocaleString('ar-EG'):'بدون تاريخ';
const money=v=>Number(v||0).toLocaleString('ar-EG')+' ج';
const iso=v=>v?new Date(v).toISOString():null;

export default function Customer360(){
 const router=useRouter(); const {id}=router.query;
 const [session,setSession]=useState(null),[role,setRole]=useState('sales'),[lead,setLead]=useState(null),[draft,setDraft]=useState({}),[data,setData]=useState({activities:[],calls:[],followups:[],appointments:[],reservations:[],deals:[],payments:[],units:[]}),[tab,setTab]=useState('overview'),[action,setAction]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const allowed={editLead:can(role,PERMISSIONS.LEADS_UPDATE),calls:can(role,PERMISSIONS.CALLS_MANAGE),followups:can(role,PERMISSIONS.FOLLOWUPS_MANAGE),appointments:can(role,PERMISSIONS.APPOINTMENTS_MANAGE),reservations:can(role,PERMISSIONS.RESERVATIONS_MANAGE),deals:can(role,PERMISSIONS.DEALS_MANAGE),finance:can(role,PERMISSIONS.FINANCE_MANAGE)};
 const load=useCallback(async()=>{if(!id)return;setLoading(true);setError('');const {data:s,error:e}=await supabase.auth.getSession();if(e||!s.session){window.location.href='/';return;}setSession(s.session);const {data:r}=await supabase.from('user_roles').select('role').eq('id',s.session.user.id).maybeSingle();setRole(normalizeRole(r?.role));const lr=await supabase.from('leads').select('*').eq('id',id).single();if(lr.error||!lr.data){setError('لم يتم العثور على العميل أو لا تملك صلاحية الوصول.');setLoading(false);return;}setLead(lr.data);setDraft({name:lr.data.name||'',phone:lr.data.phone||'',email:lr.data.email||'',status:lr.data.status||'New Lead',temperature:lr.data.temperature||'Warm',budget:lr.data.budget??'',preferred_area:lr.data.preferred_area||'',desired_unit_type:lr.data.desired_unit_type||''});const names=['activities','calls','followups','appointments','reservations','deals','units'];const queries=await Promise.all(names.map(async n=>{const table=n==='activities'?'lead_logs':n;let q=supabase.from(table).select('*');if(n!=='units')q=q.eq('lead_id',id);q=q.order('created_at',{ascending:false});return [n,await q];}));const next={};queries.forEach(([n,q])=>{next[n]=q.data||[];});const ids=(next.deals||[]).map(x=>x.id);if(ids.length){const p=await supabase.from('deal_payments').select('*').in('deal_id',ids).order('due_date',{ascending:true});next.payments=p.data||[];}else next.payments=[];setData(next);setLoading(false);},[id]);
 useEffect(()=>{load();},[load]);
 const log=async(actionType,content)=>{if(session?.user)await supabase.from('lead_logs').insert([{lead_id:id,user_email:session.user.email||'',action_type:actionType,content}]);};
 const updateLead=async e=>{e.preventDefault();if(busy)return;setBusy(true);const patch={name:String(draft.name||'').trim(),phone:String(draft.phone||'').trim(),email:String(draft.email||'').trim()||null,status:draft.status,temperature:draft.temperature,budget:draft.budget===''?null:Number(draft.budget),preferred_area:draft.preferred_area||null,desired_unit_type:draft.desired_unit_type||null};if(!patch.name||!patch.phone){setNotice('الاسم ورقم الهاتف مطلوبان.');setBusy(false);return;}try{const token=session?.access_token;if(!token){setNotice('انتهت الجلسة.');setBusy(false);return;}const response=await fetch('/api/leads/update',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({id,name:patch.name,phone:patch.phone,email:patch.email,status:patch.status,temperature:patch.temperature,budget:patch.budget,preferred_area:patch.preferred_area,desired_unit_type:patch.desired_unit_type})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'تعذر تحديث بيانات العميل.');await log('LEAD_UPDATED','تم تعديل بيانات العميل');setAction('');await load();}catch(e2){setNotice(e2.message||'تعذر تحديث بيانات العميل.');}finally{setBusy(false);}};
 const callApi=async(method,table,recordId,patch={})=>{const token=(await supabase.auth.getSession()).data.session?.access_token;if(!token){setNotice('انتهت الجلسة.');return false;}const res=await fetch('/api/customer360/records',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({table,id:recordId,lead_id:id,patch})});const body=await res.json().catch(()=>({}));if(!res.ok){setNotice(body.error||'تعذر تنفيذ العملية');return false;}return true;};
 const editRecord=async(table,item)=>{const status=window.prompt('الحالة الجديدة:',item.status||'Pending');if(status===null)return;const notes=window.prompt('الملاحظات:',item.notes||'');if(notes===null)return;const ok=await callApi('PATCH',table,item.id,{status,notes});if(ok){await log(table.toUpperCase()+'_UPDATED','تم تعديل سجل من Customer 360');await load();}};
 const deleteRecord=async(table,item)=>{if(!window.confirm('تأكيد الحذف؟ لا يمكن التراجع عن هذه العملية.'))return;const ok=await callApi('DELETE',table,item.id);if(ok){await log(table.toUpperCase()+'_DELETED','تم حذف سجل من Customer 360');await load();}};
 const insert=async(e,table,payload,label)=>{e.preventDefault();if(busy)return;setBusy(true);try{const token=(await supabase.auth.getSession()).data.session?.access_token;if(!token){setNotice('انتهت الجلسة.');return;}const response=await fetch('/api/customer360/records',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({table,lead_id:id,record:payload})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'تعذر حفظ السجل.');await log(label,'تمت إضافة سجل جديد');setAction('');await load();}catch(error){setNotice(error.message||'تعذر حفظ السجل.');}finally{setBusy(false);}};
 const timeline=useMemo(()=>[...data.activities.map(x=>({...x,k:'نشاط',d:x.created_at,h:x.action_type,b:x.content})),...data.calls.map(x=>({...x,k:'مكالمة',d:x.call_at||x.created_at,h:x.outcome,b:x.notes})),...data.followups.map(x=>({...x,k:'متابعة',d:x.followup_date||x.created_at,h:x.status,b:x.notes})),...data.appointments.map(x=>({...x,k:'موعد',d:x.scheduled_at||x.created_at,h:x.type,b:x.notes})),...data.reservations.map(x=>({...x,k:'حجز',d:x.created_at,h:x.status,b:x.notes})),...data.deals.map(x=>({...x,k:'صفقة',d:x.created_at,h:x.status,b:x.notes}))].sort((a,b)=>new Date(b.d||0)-new Date(a.d||0)),[data]);
 const RecordList=({table,items,empty,fields=[]})=><div>{items.length?items.map(item=><div key={item.id} style={{borderBottom:'1px solid #e5d6be',padding:'13px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><strong>{text(item.outcome||item.type||item.status||item.title||'سجل')}</strong><span style={T.muted}>{date(item.call_at||item.followup_date||item.scheduled_at||item.created_at)}</span></div><div style={T.muted}>{text(item.notes||item.content||item.description)}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}>{fields.map(f=><span key={f} style={{...T.secondary,padding:'4px 8px',fontSize:12}}>{f}: {text(item[f])}</span>)}{table!=='lead_logs'&&<><button style={T.secondary} onClick={()=>editRecord(table,item)}>تعديل</button><button style={T.danger} onClick={()=>deleteRecord(table,item)}>حذف</button></>}</div></div>):<div style={T.muted}>{empty}</div>}</div>;
 const Field=({label,children})=><label style={{display:'grid',gap:6,fontWeight:700,fontSize:13}}><span>{label}</span>{children}</label>;
 const total= data.deals.reduce((s,x)=>s+Number(x.deal_value||0),0),paid=data.payments.filter(x=>x.status==='Paid').reduce((s,x)=>s+Number(x.amount||0),0),due=data.payments.filter(x=>x.status!=='Paid'&&x.status!=='Cancelled').reduce((s,x)=>s+Number(x.amount||0),0);
 if(loading)return <main dir="rtl" style={T.page}>جاري تحميل ملف العميل...</main>;if(error)return <main dir="rtl" style={T.page}><div style={T.shell}><section style={T.card}>{error}<br/><button style={T.secondary} onClick={()=>router.back()}>رجوع</button></section></div></main>;if(!lead)return null;
 return <main dir="rtl" style={T.page}><div style={T.shell}>
 <header style={{...T.card,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><span style={{...T.secondary,padding:'5px 9px',fontSize:12}}>Customer 360</span><h1 style={T.title}>{text(lead.name)}</h1><div style={T.muted}>{text(lead.phone)} {lead.email?'— '+lead.email:''}</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button style={T.secondary} onClick={()=>router.back()}>رجوع</button><button style={T.secondary} onClick={load}>تحديث</button><button style={T.button} onClick={()=>window.open('https://wa.me/'+String(lead.phone||'').replace(/[^0-9]/g,''),'_blank','noopener,noreferrer')}>واتساب</button></div></header>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:10,marginBottom:16}}>{[['المكالمات',data.calls.length],['المتابعات',data.followups.length],['المواعيد',data.appointments.length],['الحجوزات',data.reservations.length],['الصفقات',data.deals.length],['قيمة الصفقات',money(total)]].map(([l,v])=><div key={l} style={T.card}><div style={T.muted}>{l}</div><strong style={{fontSize:21,color:'#765522'}}>{v}</strong></div>)}</section>
 <section style={T.card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:8}}><h2 style={T.title}>بيانات العميل</h2>{allowed.editLead&&<button style={T.button} onClick={()=>setAction(action==='editLead'?'':'editLead')}>تعديل العميل</button>}</div><div style={T.grid}>{[['الحالة',lead.status],['الحرارة',lead.temperature],['المصدر',lead.lead_source],['الميزانية',lead.budget?money(lead.budget):'غير محدد'],['المنطقة',lead.preferred_area||lead.preferred_location],['نوع الوحدة',lead.desired_unit_type||lead.unit_type]].map(([l,v])=><div key={l}><div style={T.muted}>{l}</div><strong>{text(v)}</strong></div>)}</div></section>
 {action==='editLead'&&<form onSubmit={updateLead} style={T.card}><h2 style={T.title}>تعديل بيانات العميل</h2><div style={T.grid}><Field label="الاسم"><input style={T.input} value={draft.name||''} onChange={e=>setDraft({...draft,name:e.target.value})} required/></Field><Field label="الهاتف"><input style={T.input} value={draft.phone||''} onChange={e=>setDraft({...draft,phone:e.target.value})} required/></Field><Field label="البريد"><input style={T.input} type="email" value={draft.email||''} onChange={e=>setDraft({...draft,email:e.target.value})}/></Field><Field label="الحالة"><select style={T.input} value={draft.status||'New Lead'} onChange={e=>setDraft({...draft,status:e.target.value})}>{['New Lead','Contacted','Interested','Meeting Set','Closed Won','Lost'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="الحرارة"><select style={T.input} value={draft.temperature||'Warm'} onChange={e=>setDraft({...draft,temperature:e.target.value})}>{['Cold','Warm','Hot'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="الميزانية"><input style={T.input} type="number" value={draft.budget??''} onChange={e=>setDraft({...draft,budget:e.target.value})}/></Field><Field label="المنطقة"><input style={T.input} value={draft.preferred_area||''} onChange={e=>setDraft({...draft,preferred_area:e.target.value})}/></Field><Field label="نوع الوحدة"><input style={T.input} value={draft.desired_unit_type||''} onChange={e=>setDraft({...draft,desired_unit_type:e.target.value})}/></Field></div><button disabled={busy} style={{...T.button,marginTop:12}}>حفظ التعديلات</button></form>}
 <section style={{...T.card,display:'flex',gap:8,flexWrap:'wrap'}}>{allowed.calls&&<button style={T.secondary} onClick={()=>setAction(action==='call'?'':'call')}>+ مكالمة</button>}{allowed.followups&&<button style={T.secondary} onClick={()=>setAction(action==='followup'?'':'followup')}>+ متابعة</button>}{allowed.appointments&&<button style={T.secondary} onClick={()=>setAction(action==='appointment'?'':'appointment')}>+ موعد</button>}{allowed.reservations&&<button style={T.secondary} onClick={()=>setAction(action==='reservation'?'':'reservation')}>+ حجز</button>}{allowed.deals&&<button style={T.button} onClick={()=>setAction(action==='deal'?'':'deal')}>+ صفقة</button>}{allowed.finance&&data.deals.length>0&&<button style={T.secondary} onClick={()=>setAction(action==='payment'?'':'payment')}>+ قسط</button>}</section>
 {action==='deal'&&<form style={T.card} onSubmit={e=>{const f=new FormData(e.currentTarget);return insert(e,'deals',{lead_id:id,unit_id:f.get('unit_id')||null,sales_person:session.user.id,deal_value:Number(f.get('deal_value')||0),down_payment:Number(f.get('down_payment')||0),installment_months:f.get('installment_months')?Number(f.get('installment_months')):null,payment_frequency:f.get('payment_frequency')||'monthly',status:'Pending',contract_date:f.get('contract_date')||null,notes:f.get('notes')||null},'DEAL_CREATED')}}><h2 style={T.title}>إدارة صفقة جديدة</h2><div style={T.grid}><Field label="الوحدة"><select name="unit_id" style={T.input}><option value="">بدون وحدة</option>{data.units.map(u=><option key={u.id} value={u.id}>{u.unit_number||u.title} — {money(u.price)}</option>)}</select></Field><Field label="قيمة الصفقة"><input name="deal_value" type="number" min="0" required style={T.input}/></Field><Field label="المقدم"><input name="down_payment" type="number" min="0" style={T.input}/></Field><Field label="مدة التقسيط بالشهور"><input name="installment_months" type="number" min="0" style={T.input}/></Field><Field label="الدفع"><select name="payment_frequency" style={T.input}><option value="monthly">شهري</option><option value="quarterly">ربع سنوي</option><option value="yearly">سنوي</option></select></Field><Field label="تاريخ التعاقد"><input name="contract_date" type="date" style={T.input}/></Field><Field label="ملاحظات"><input name="notes" style={T.input}/></Field></div><button disabled={busy} style={{...T.button,marginTop:12}}>حفظ الصفقة</button></form>}
 {action==='payment'&&<form style={T.card} onSubmit={e=>{const f=new FormData(e.currentTarget);return insert(e,'deal_payments',{deal_id:f.get('deal_id'),installment_no:Number(f.get('installment_no')),due_date:f.get('due_date'),amount:Number(f.get('amount')),status:'Pending',notes:f.get('notes')||null},'PAYMENT_CREATED')}}><h2 style={T.title}>إضافة قسط / دفعة</h2><div style={T.grid}><Field label="الصفقة"><select name="deal_id" required style={T.input}>{data.deals.map(d=><option key={d.id} value={d.id}>{d.id.slice(0,8)} — {money(d.deal_value)}</option>)}</select></Field><Field label="رقم القسط"><input name="installment_no" type="number" min="1" required style={T.input}/></Field><Field label="الاستحقاق"><input name="due_date" type="date" required style={T.input}/></Field><Field label="المبلغ"><input name="amount" type="number" min="0" required style={T.input}/></Field><Field label="ملاحظات"><input name="notes" style={T.input}/></Field></div><button disabled={busy} style={{...T.button,marginTop:12}}>حفظ القسط</button></form>}
 {notice&&<div style={{...T.card,color:'#9b3e30'}}>{notice}</div>}
 <section style={T.card}><h2 style={T.title}>الملخص المالي</h2><div style={T.grid}><div><div style={T.muted}>إجمالي الصفقات</div><strong>{money(total)}</strong></div><div><div style={T.muted}>المدفوع</div><strong style={{color:'#2d7a58'}}>{money(paid)}</strong></div><div><div style={T.muted}>المتبقي حسب الأقساط</div><strong style={{color:'#9b3e30'}}>{money(due)}</strong></div><div><div style={T.muted}>عدد الأقساط</div><strong>{data.payments.length}</strong></div></div></section>
 <nav style={{...T.card,display:'flex',gap:8,flexWrap:'wrap'}}>{[['overview','نظرة عامة'],['deals','الصفقات'],['payments','الأقساط والمدفوعات'],['calls','المكالمات'],['followups','المتابعات'],['appointments','المواعيد'],['reservations','الحجوزات'],['timeline','الخط الزمني']].map(([k,l])=><button key={k} style={tab===k?T.button:T.secondary} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {tab==='overview'&&<section style={T.card}><h2 style={T.title}>نظرة عامة على العميل</h2><RecordList table="lead_logs" items={timeline} empty="لا يوجد نشاط مسجل." fields={['k']}/></section>}
 {tab==='timeline'&&<section style={T.card}><h2 style={T.title}>الخط الزمني الموحد</h2><RecordList table="lead_logs" items={timeline} empty="لا يوجد نشاط مرتبط بالعميل." fields={['k']}/></section>}
 {tab==='calls'&&<section style={T.card}><h2 style={T.title}>المكالمات</h2><RecordList table="calls" items={data.calls} empty="لا توجد مكالمات." fields={['outcome','duration_seconds']}/></section>}
 {tab==='followups'&&<section style={T.card}><h2 style={T.title}>المتابعات</h2><RecordList table="followups" items={data.followups} empty="لا توجد متابعات." fields={['status','type']}/></section>}
 {tab==='appointments'&&<section style={T.card}><h2 style={T.title}>المواعيد</h2><RecordList table="appointments" items={data.appointments} empty="لا توجد مواعيد." fields={['status','type']}/></section>}
 {tab==='reservations'&&<section style={T.card}><h2 style={T.title}>الحجوزات</h2><RecordList table="reservations" items={data.reservations} empty="لا توجد حجوزات." fields={['status','reservation_amount','contract_value']}/></section>}
 {tab==='deals'&&<section style={T.card}><h2 style={T.title}>إدارة الصفقات</h2><RecordList table="deals" items={data.deals} empty="لا توجد صفقات." fields={['status','deal_value','down_payment','installment_months','payment_frequency']}/></section>}
 {tab==='payments'&&<section style={T.card}><h2 style={T.title}>جدول الأقساط والمدفوعات</h2><RecordList table="deal_payments" items={data.payments} empty="لا توجد أقساط." fields={['installment_no','amount','due_date','status']}/></section>}
 </div></main>;
}
