import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabaseClient';

export default function FoldersPage() {
  const [loading, setLoading] = useState(true), [user, setUser] = useState(null), [folders, setFolders] = useState([]), [leads, setLeads] = useState([]), [name, setName] = useState(''), [selected, setSelected] = useState(''), [search, setSearch] = useState(''), [message, setMessage] = useState('');
  const load = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return (window.location.href = '/'); setUser(session.user); const [f, l] = await Promise.all([supabase.from('lead_folders').select('id,name').eq('active', true).order('name'), supabase.from('leads').select('id,name,phone,folder').order('created_at', { ascending: false })]); setFolders(f.data || []); setLeads(l.data || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => leads.filter(x => (selected === '__none__' ? !x.folder : selected ? x.folder === selected : true) && (!search || (x.name || '').toLowerCase().includes(search.toLowerCase()) || (x.phone || '').includes(search))), [leads, selected, search]);
  const create = async e => { e.preventDefault(); const n = name.trim(); if (!n) return; const { error } = await supabase.from('lead_folders').insert([{ name: n, created_by: user.id, active: true }]); setMessage(error ? error.message : 'تم إنشاء المجلد'); if (!error) { setName(''); load(); } };
  const move = async (id, folder) => { const { error } = await supabase.from('leads').update({ folder: folder || null }).eq('id', id); if (error) setMessage(error.message); else setLeads(xs => xs.map(x => x.id === id ? { ...x, folder: folder || null } : x)); };
  if (loading) return <div style={page}>جاري التحميل...</div>;
  return <main dir="rtl" style={page}><div style={{ maxWidth: 1100, margin: 'auto' }}><header style={head}><div><h1 style={{ color: '#fbbf24', margin: 0 }}>📁 مجلدات العملاء</h1><p style={{ color: '#94a3b8' }}>تنظيم العملاء ونقلهم بين المجلدات.</p></div><button onClick={() => window.location.assign('/dashboard#leads')} style={btn('#111827', '#fbbf24')}>العودة للعملاء</button></header><section style={card}><h2 style={h2}>إنشاء مجلد</h2><form onSubmit={create} style={row}><input required value={name} onChange={e => setName(e.target.value)} placeholder="اسم المجلد" style={input}/><button style={btn('#fbbf24', '#0c0f17')}>+ إنشاء</button></form>{message && <p style={{ color: '#fbbf24' }}>{message}</p>}</section><section style={card}><h2 style={h2}>المجلدات</h2><div style={row}><button onClick={() => setSelected('')} style={btn(!selected ? '#fbbf24' : '#111827', '#fbbf24')}>كل العملاء</button><button onClick={() => setSelected('__none__')} style={btn(selected === '__none__' ? '#fbbf24' : '#111827', '#fbbf24')}>بدون مجلد</button>{folders.map(f => <button key={f.id} onClick={() => setSelected(f.name)} style={btn(selected === f.name ? '#fbbf24' : '#111827', '#fbbf24')}>{f.name}</button>)}</div><input value={search} onChange={e => setSearch(e.target.value)} placeholder="بحث باسم العميل أو الهاتف" style={{ ...input, width: '100%', margin: '14px 0' }}/><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 600, borderCollapse: 'collapse' }}><thead><tr><th style={cell}>العميل</th><th style={cell}>الهاتف</th><th style={cell}>المجلد</th><th style={cell}>نقل</th></tr></thead><tbody>{visible.map(x => <tr key={x.id}><td style={cell}>{x.name || '-'}</td><td style={cell}>{x.phone || '-'}</td><td style={cell}>{x.folder || 'بدون مجلد'}</td><td style={cell}><select value={x.folder || ''} onChange={e => move(x.id, e.target.value)} style={input}><option value="">بدون مجلد</option>{folders.map(f => <option key={f.id} value={f.name}>{f.name}</option>)}</select></td></tr>)}</tbody></table></div></section></div></main>;
}
const page = { minHeight: '100vh', background: '#0c0f17', color: '#f3f4f6', padding: 20, fontFamily: 'Arial,sans-serif' }, card = { background: '#131822', border: '1px solid #273244', borderRadius: 16, padding: 18, marginBottom: 16 }, head = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap', marginBottom: 20 }, row = { display: 'flex', gap: 8, flexWrap: 'wrap' }, h2 = { color: '#fbbf24', fontSize: 18 }, input = { background: '#0c0f17', color: '#fff', border: '1px solid #475569', borderRadius: 10, padding: '11px 12px', minWidth: 200 }, btn = (background, color) => ({ background, color, border: '1px solid #fbbf24', borderRadius: 10, padding: '11px 16px', fontWeight: 700 }), cell = { padding: 12, textAlign: 'right', borderBottom: '1px solid #273244' };
