import { useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';

const c = { bg: '#f5efe3', surface: '#fffaf0', border: '#d9c5a4', gold: '#b08a4a', dark: '#765522', text: '#3f321f', muted: '#806f56', danger: '#a7352b' };
const field = { width: '100%', minHeight: 44, padding: '10px 12px', borderRadius: 10, border: `1px solid ${c.border}`, background: c.surface, color: c.text, font: 'inherit', boxSizing: 'border-box' };
const button = { minHeight: 44, padding: '10px 16px', border: 0, borderRadius: 10, background: c.gold, color: '#fffaf0', fontWeight: 800, cursor: 'pointer' };

export default function Settings() {
  const [session, setSession] = useState(null), [language, setLanguage] = useState('ar'), [password, setPassword] = useState(''), [confirm, setConfirm] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  useEffect(() => { (async () => { const { data } = await supabase.auth.getSession(); if (!data?.session) return (window.location.href = '/'); setSession(data.session); const { data: pref } = await supabase.from('user_preferences').select('value').eq('user_id', data.session.user.id).eq('key', 'language').maybeSingle(); if (pref?.value === 'en') setLanguage('en'); })(); }, []);
  const saveLanguage = async (e) => { e.preventDefault(); setBusy(true); setMessage(''); setError(''); const { error: err } = await supabase.from('user_preferences').upsert({ user_id: session.user.id, key: 'language', value: language }, { onConflict: 'user_id,key' }); if (err) setError(err.message); else { localStorage.setItem('arcova-language', language); setMessage('تم حفظ اللغة بنجاح.'); } setBusy(false); };
  const savePassword = async (e) => { e.preventDefault(); setMessage(''); setError(''); if (password.length < 8) return setError('كلمة المرور يجب أن تكون 8 أحرف على الأقل.'); if (password !== confirm) return setError('تأكيد كلمة المرور غير مطابق.'); setBusy(true); const { error: err } = await supabase.auth.updateUser({ password }); if (err) setError(err.message); else { setPassword(''); setConfirm(''); setMessage('تم تغيير كلمة المرور بنجاح.'); } setBusy(false); };
  const logout = async () => { await supabase.auth.signOut(); window.location.href = '/'; };
  return <main dir="rtl" style={{ minHeight: '100vh', background: c.bg, color: c.text, padding: 24, fontFamily: 'Tahoma, Segoe UI, Arial, sans-serif' }}><div style={{ maxWidth: 880, margin: '0 auto' }}><header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 24 }}><div><b style={{ color: c.gold }}>ARCOVA CRM</b><h1 style={{ color: c.dark, margin: '6px 0' }}>الإعدادات</h1><span style={{ color: c.muted }}>{session?.user?.email || ''}</span></div><div style={{ display: 'flex', gap: 8 }}><button onClick={() => window.location.href = '/dashboard'} style={{ ...button, background: c.surface, color: c.dark, border: `1px solid ${c.border}` }}>العودة</button><button onClick={logout} style={{ ...button, background: '#fff1ee', color: c.danger, border: '1px solid #c66a61' }}>تسجيل الخروج</button></div></header>{message && <div role="status" style={{ padding: 12, marginBottom: 16, borderRadius: 10, background: '#e8f4ec', color: '#2d7a58' }}>{message}</div>}{error && <div role="alert" style={{ padding: 12, marginBottom: 16, borderRadius: 10, background: '#fff1ee', color: c.danger }}>{error}</div>}<section style={{ background: c.surface, border: `1px solid ${c.border}`, borderRadius: 18, padding: 22, marginBottom: 18 }}><h2 style={{ color: c.dark }}>اللغة</h2><p style={{ color: c.muted }}>اختيار اللغة يتم حفظه في حساب المستخدم.</p><form onSubmit={saveLanguage} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 14, alignItems: 'end' }}><label>لغة النظام<select value={language} onChange={e => setLanguage(e.target.value)} style={field}><option value="ar">العربية</option><option value="en">English</option></select></label><button disabled={busy} style={button}>حفظ اللغة</button></form></section><section style={{ background: c.surface, border: `1px solid ${c.border}`, borderRadius: 18, padding: 22 }}><h2 style={{ color: c.dark }}>تغيير كلمة المرور</h2><p style={{ color: c.muted }}>استخدم كلمة مرور قوية لا تقل عن 8 أحرف.</p><form onSubmit={savePassword} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 14, alignItems: 'end' }}><label>كلمة المرور الجديدة<input type="password" minLength="8" required autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} style={field} /></label><label>تأكيد كلمة المرور<input type="password" minLength="8" required autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} style={field} /></label><button disabled={busy} style={button}>تحديث كلمة المرور</button></form></section></div><style jsx>{`label{display:flex;flex-direction:column;gap:8px;font-weight:700;line-height:1.8}@media(max-width:640px){main{padding:14px!important}}`}</style></main>;
}
